import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { connectDB } from './config/db.js';
import authRoutes from './routes/auth.js';
import tourRoutes from './routes/tours.js';
import inquiryRoutes from './routes/inquiries.js';
import uploadRoutes from './routes/upload.js';
import settingsRoutes from './routes/settings.js';

const app=express();
app.use(cors({origin:process.env.CLIENT_URL ? process.env.CLIENT_URL.split(',') : true, credentials:true}));
app.use(express.json({limit:'2mb'}));
app.get('/health',(req,res)=>res.json({ok:true,service:'Secret Tours Egypt API'}));
app.use('/auth',authRoutes);
app.use('/tours',tourRoutes);
app.use('/inquiries',inquiryRoutes);
app.use('/upload',uploadRoutes);
app.use('/settings',settingsRoutes);
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:err.message||'Server error'})});
const port=process.env.PORT||5000;
connectDB().then(()=>app.listen(port,()=>console.log(`API running on :${port}`))).catch(err=>{console.error('DB connection failed:',err.message);process.exit(1)});
